<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <title>View/modify task</title>
</head>
<body class="container mx-auto max-w-2xl mt-20 bg-amber-100">
<div>
    <h1 class="text-4xl font-bold tracking-tight sm:text-6xl text-center my-16 ">Here is your task!</h1>
    <form action="modify" method="post" controler= >
    <div class="max-w-sm mx-auto ">
        <fieldset class= "grid justify-center border border-blue-700 p-4 bg-blue-200">
        <div class="m-3">   
        <label for="task">Task
                <input type="text" id="task" required class=" border border-black rounded-xl">
            </label>
        </div> 
        <div class="m-3">
            <label for="status" >Status 
                <select id="status" name="status" class="border border-black rounded-xl bg-white"> 
                <option value="pending">Started</option>
                <option value="progress">In progress</option>
                <option value="completed">completed</option>
                </select>
        </div>
            <div class="m-3" >
                <label for="dateStart"> Starting date 
                <input type="date" id="dateStart" class=" border-black rounded-xl" readonly>
                </label>
            </div>
            <div class="m-3" >
                <label for="endingDate"> Ending date
                <input type="date" id="endingDate" class=" border-black rounded-xl" readonly>
                </label>
            </div>
        <div  class=" text-center m-5">            
            <input type="submit" value="go back" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded mr-5 cursor-pointer">
            <input type="submit" value="save task" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded cursor-pointer">
        </div>         
            
    </fieldset>
    </div>    
    
    </form>
</div>
</body>
</html>