<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
</head>
    <title>User Registration</title>
</head>
<body class="bg-amber-100">
    <div class="mx-auto max-w-2xl mt-20 ">
    <h1 class="text-4xl font-bold tracking-tight sm:text-6xl text-center my-16 ">¡Welcome to task manager!</h1>
    <form action="post" method="post" controler= >
    <div class="grid grid-cols-1 max-w-sm mx-auto">
        <fieldset class=" border border-black p-8 text-center bg-amber-200">
        <div class="my-5">   
        <label for="username">Username
                <input type="text" id="username" required class="border border-black rounded-xl">
            </label>
        </div> 
        <div class="my-5">
            <label for="password">Password <input type="text" id="password" required class="border border-black rounded-xl"></label>
        </div>
        <div >            
            <input type="submit" value="login" class="mr-5" >
            <input type="submit" value="create account">
        </div>
            
        </fieldset>
    </div>    
    
    </form>
    </div>
    
</body>
</html>